version: "1"
services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "4000:4000"
    environment:
      ATLAS_URI: "${ATLAS_URI}"
      JWT_SECRET: "${JWT_SECRET}"
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://server:4000
